"""empty message

Revision ID: 2540ceeaa94
Revises: 20e70b3b6dd
Create Date: 2015-11-10 19:59:45.154705

"""

# revision identifiers, used by Alembic.
revision = '2540ceeaa94'
down_revision = '20e70b3b6dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('cbom', schema=None) as batch_op:
     #   batch_op.drop_column('file_name')

    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('cbom', schema=None) as batch_op:
   #     batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=265), nullable=True))

    ### end Alembic commands ###
