"""empty message

Revision ID: 316c420142
Revises: 1e082cd44f3e
Create Date: 2015-11-05 19:40:18.272988

"""

# revision identifiers, used by Alembic.
revision = '316c420142'
down_revision = '1e082cd44f3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=265), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    #sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cbom')
    ### end Alembic commands ###
