"""empty message

Revision ID: 35644e357aa
Revises: 316c420142
Create Date: 2015-11-08 21:15:10.690408

"""

# revision identifiers, used by Alembic.
revision = '35644e357aa'
down_revision = '316c420142'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cbom_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cbom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cbom_id'], ['cbom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cbom_row')
    op.drop_table('users')
    ### end Alembic commands ###
