"""empty message

Revision ID: 3e7e93ac5f0
Revises: fa04a25a3d
Create Date: 2015-11-11 22:57:01.066595

"""

# revision identifiers, used by Alembic.
revision = '3e7e93ac5f0'
down_revision = 'fa04a25a3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cbom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('cbom_row', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cbom_row', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    with op.batch_alter_table('cbom', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    ### end Alembic commands ###
