"""empty message

Revision ID: 4851774ea63
Revises: 35644e357aa
Create Date: 2015-11-08 21:25:39.345248

"""

# revision identifiers, used by Alembic.
revision = '4851774ea63'
down_revision = '35644e357aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cbom_row', sa.Column('int_part_num', sa.String(length=50), nullable=True))
    op.add_column('cbom_row', sa.Column('man_part_num', sa.String(length=50), nullable=True))
    op.add_column('cbom_row', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('cbom_row', sa.Column('unit_price', sa.Numeric(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cbom_row', 'unit_price')
    op.drop_column('cbom_row', 'quantity')
    op.drop_column('cbom_row', 'man_part_num')
    op.drop_column('cbom_row', 'int_part_num')
    ### end Alembic commands ###
