"""empty message

Revision ID: 492ff776cdf
Revises: 3e7e93ac5f0
Create Date: 2015-11-11 11:47:56.743972

"""

# revision identifiers, used by Alembic.
revision = '492ff776cdf'
down_revision = '3e7e93ac5f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cbom_row', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cbom_row', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    ### end Alembic commands ###
