"""empty message

Revision ID: fa04a25a3d
Revises: 2540ceeaa94
Create Date: 2015-11-10 20:11:45.194889

"""

# revision identifiers, used by Alembic.
revision = 'fa04a25a3d'
down_revision = '2540ceeaa94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cbom_row', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_cool_columns', sa.String(length=10), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cbom_row', schema=None) as batch_op:
        batch_op.drop_column('new_cool_columns')

    ### end Alembic commands ###
